site_name: Supbot2
site_description: Unoffical WhatsApp Automation Library for Python.
repo_url: https://github.com/adsau59/Supbot2
site_author: Adam Saudagar
edit_uri: ""

nav:
    - Home: index.md
    - How to Use:
        - Overview: how-to-use/overview.md
        - Models: how-to-use/models.md
        - Config: how-to-use/config.md
    - Services:
        - Helper: services/helper.md
        - Action: services/action.md
        - Event: services/event.md
        
copyright: Copyright &copy; 2020 <a href="https://twitter.com/adam_saudagar">Adam Saudagar</a>
